/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 05.08.2026 14:21:17

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 8
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 10128;
#else
constexpr int kTensorArenaSize = 9104;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,3960 } };
const TfArray<1, float> quant0_scale = { 1, { 0.00390625, } };
const TfArray<1, int> quant0_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 99, 40, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 99, 1, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 50, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data4[4] = { 1, 50, 1, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data5[2] = { -1, 400, };
const TfArray<1, int> tensor_dimension5 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data6[4] = { -1577, -97, -665, 1691, };
const TfArray<1, float> quant6_scale = { 1, { 0.00074123404920101166, } };
const TfArray<1, int> quant6_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data7[4*400] = { 
  -2, 13, 7, -10, -8, 7, -7, 19, 1, -11, -82, -49, -10, 0, -4, 14, -4, 5, 4, -14, -48, 0, -30, 6, -14, -35, -25, -53, -19, 10, -23, 7, 0, 9, 15, -86, -42, 0, -30, 1, -22, -22, -5, -73, -19, 2, -11, 8, 3, 7, 8, -36, -49, 2, -2, 2, -33, -38, -45, -19, -8, 12, 1, 15, -1, 8, 14, -61, -21, 6, -23, 0, -20, -6, -93, -21, 6, 6, -24, 18, 5, 9, 10, -17, -26, 3, -9, 4, -13, -18, -15, 3, -17, 6, -5, 8, -1, 4, 11, -75, -19, 3, -6, 4, -9, -15, -76, -44, -10, 9, 14, 20, -7, 9, 1, -76, -16, -1, -11, 3, -16, -15, -29, -37, -26, 8, -5, 9, -3, 6, 3, -94, -49, 4, -17, 3, -12, -33, -82, -57, -8, 12, -13, 19, -5, 8, 14, -50, -25, 6, 5, 4, 1, -28, -76, -50, -23, 17, -7, 11, -5, 9, 10, 2, -40, 5, -6, 5, -15, -10, -26, 4, -10, 10, -5, 6, -5, 6, 6, 4, -42, 10, -13, 13, -21, -21, -57, -45, -11, 12, -4, 11, 5, 7, 9, -18, -36, 3, -18, 0, -8, -28, 6, -64, -10, 9, -6, 18, 2, 12, 4, -30, -37, 5, -14, 0, 0, -23, -34, -30, 2, 8, 2, 8, -8, 2, 6, -14, -50, 4, -13, 5, -17, -32, -124, -50, -34, 13, -15, 16, -5, 3, 14, -11, -45, 3, -12, 4, -14, -29, 7, -43, -20, 17, -27, 13, -1, 7, 15, -33, -27, 4, -12, 10, -12, -18, -56, -3, 1, 8, -6, 12, 2, 3, 15, -16, -38, 8, -12, 0, -24, -14, -65, -42, 11, 1, -2, 12, -8, 6, 5, -35, -32, -2, -2, 3, -17, -25, -62, -10, -2, 17, 0, 19, -3, 2, 11, -56, -24, -2, -5, -1, -19, -24, -74, -70, -17, 3, -19, 17, -5, 9, -1, -64, -27, 17, -15, -1, -28, -14, -72, -39, -27, 20, -10, 10, -5, 4, 5, -62, -47, 4, -19, 2, -27, -23, -62, 5, -45, 11, -40, 10, -8, 6, 9, -41, -52, 8, -2, 12, -14, -12, -59, -61, -11, 14, -2, 18, -14, 17, 10, -53, -66, 3, -8, 6, -24, -33, -102, -61, -18, 13, -26, 15, 3, 18, 13, 21, -57, 13, -14, 5, -18, -16, -75, -43, -13, 12, -2, 24, 
  4, -31, 3, -16, 5, -22, -12, 7, 6, 14, -4, 14, 9, 7, 4, -11, 2, -26, 2, -63, 13, -15, -2, 9, -1, 11, -6, 14, -27, 7, 15, -5, -3, -15, 1, -36, 8, -8, -7, 4, -12, 14, -12, 12, -9, 9, 0, -13, -3, -15, 3, -65, 8, -12, -16, 0, -4, 14, 3, -1, -17, 6, 8, -15, 1, -18, 8, -9, 7, -21, -7, 2, -12, 10, -5, 10, -20, 6, 12, -14, -11, -27, 5, 21, 5, -11, -2, 7, 1, 11, -18, -1, -16, 9, 6, -13, -8, -23, 2, 33, 9, -16, -16, 6, -5, 10, 5, 9, -9, 3, 10, -13, 7, -29, 2, -54, 7, -8, -7, 4, 1, 14, 4, 10, -6, 4, 0, -9, 3, -26, 3, -1, 13, -6, 1, 5, -4, 12, 4, 11, -17, 1, 3, -2, -1, -11, 3, -23, 10, -4, -10, 8, -12, 6, -32, 12, -14, 0, 7, -3, 0, -16, 7, -39, 9, -16, -12, 3, -14, 5, -12, -6, -6, 10, 13, -9, -2, -22, -1, -36, 6, -10, -14, 8, -5, 9, -5, 7, -45, 1, 7, -8, 1, -17, 5, -37, 6, -10, -6, 8, -5, 7, -57, 26, -27, 1, 2, -6, -10, -27, 2, -78, 7, -8, 0, 6, -3, 9, -21, 21, -47, 3, 9, -4, 1, -12, 2, -34, 4, -4, -10, 4, 0, 13, -17, 25, -24, 0, 10, -4, -3, -9, 3, 5, 7, -4, -9, 3, -15, 10, -25, 7, -21, 13, 5, -19, 1, -23, -2, 2, 11, 2, -19, 1, -8, 9, -4, -6, -15, 2, 3, -10, -5, -36, 5, -64, 9, -14, -11, 8, 1, 11, -6, -1, -22, 11, 6, -12, -1, -25, 5, -27, 6, -12, -3, 3, 6, 10, -2, 9, -8, 10, 1, -12, 3, -23, 10, 16, 5, -5, -1, 8, 0, 14, -5, 16, -10, 4, -3, -7, 2, -35, 5, -20, 6, -20, -5, 8, 1, 11, -9, 8, -17, 3, 1, -9, 1, -27, 2, -25, 7, -10, -1, 5, -3, 14, -5, 9, -6, 9, 13, -1, 1, -21, 5, -40, 6, -21, -4, 5, -6, 8, -12, 8, -12, 8, 7, -7, 6, -23, 8, -19, 6, -29, -8, 5, -4, 12, 4, 33, -12, 8, 10, -16, 0, -13, 5, -36, 20, -26, -15, 10, -13, 7, 16, 17, -24, 16, 2, -15, 
  -25, 6, 6, 7, -1, -12, 2, -43, -3, 6, -54, 11, -2, 9, -29, -12, -21, 9, 4, 4, 8, 1, 15, -44, -34, 12, -49, 4, 16, -8, -11, 0, -10, 9, 8, 2, 4, -4, 5, -18, 0, 10, -38, 18, 8, -4, -5, -9, -8, 4, 5, -64, 8, -7, 5, -7, -5, 8, -28, 6, 4, -3, -16, 4, -15, 0, 7, -23, 8, -4, 3, -6, -13, 8, -32, 2, -42, -2, -7, -16, -16, 7, 1, -22, 4, -5, -1, -16, -19, 12, -36, -12, 12, -1, -13, -13, -20, 2, 4, -23, 4, -7, 4, -22, -14, 11, -109, -2, 0, -10, -30, -9, -7, 5, 6, 24, 3, -6, 1, -12, -27, 6, -33, 12, 12, -2, -20, -8, -23, 5, 3, 6, 10, -11, 6, -6, -10, 13, -49, -1, 11, -4, -2, -13, -25, 0, 7, -11, 8, -11, 2, -12, -22, 13, 19, 5, 10, -8, -12, -1, -31, -2, 3, -7, 5, 0, 8, -10, -15, 10, -127, -3, 6, -15, -15, -9, -22, 0, 3, -29, 4, -10, 10, -19, -11, 11, -18, -8, 23, -1, -29, -11, -16, 0, 4, 23, 9, -10, 4, 4, -13, 6, 7, 1, 7, 5, -18, -7, -11, -7, 7, 1, 6, 8, -4, -37, -22, 11, 8, 2, 5, -2, -25, 1, -9, 8, 8, -45, 4, -6, 10, -24, -15, 11, -19, -5, 20, -9, -19, -9, -4, 7, 9, -43, 8, -13, 3, -20, -9, 3, -18, -12, 3, -8, -16, -3, -17, 6, 8, -65, 9, -1, 5, -16, -30, 6, -53, 4, -14, 6, -10, -11, -29, 8, 5, 0, 4, -5, 2, -14, -8, 5, -3, -2, -6, 7, -3, -9, -29, 8, 6, -28, 7, -7, 2, -27, -23, 9, -123, -16, 0, -2, -6, -10, -14, 3, 5, -34, -3, -3, 4, -12, -11, 6, -45, 9, 11, 4, -7, -5, -11, 5, 6, 14, 5, -14, 9, -27, -19, 9, -13, 7, 12, -5, -10, -8, -34, 4, 7, 17, 8, -4, 9, -13, -6, 8, -19, 0, 1, 2, -24, 2, -36, 3, 5, -1, 7, -9, 3, -19, -18, 7, -43, -3, 3, -2, -14, -8, -17, -8, 5, 24, 8, -5, 4, -28, -6, 9, -91, 5, 14, -10, -22, -3, -32, 7, 12, 3, 10, -13, 11, -30, -2, 12, -44, -19, 12, -4, -8, -6, 
  7, -2, -20, -8, -3, -3, 14, -5, -10, -38, -6, -8, -6, -37, 5, -3, 5, -3, -23, -8, -13, -4, 6, -1, 7, -25, -25, -2, 1, -13, -10, -25, 7, -9, -33, 12, -12, -2, 10, -6, 3, -27, -3, 0, 1, -21, -2, -7, 3, -1, -20, 71, -8, 0, 6, -7, 7, -13, -9, -2, 3, -22, -8, -11, 0, 0, -32, 15, -18, 3, 13, -4, 2, -25, 23, -10, 17, -15, -1, -16, 10, 1, -31, -27, -14, 2, 4, -3, 2, -18, 3, -7, -1, -27, -8, -13, 8, 0, -18, -23, -5, 4, 6, -6, 2, -18, 17, 2, 1, -3, -10, -11, 4, -6, -30, -10, -9, 0, 10, -6, 1, -28, -19, -10, -1, -32, 1, -11, 10, -2, -24, -2, -14, 1, 8, -11, 0, -18, 24, 12, -2, -14, -5, -16, 14, -9, -32, 17, -8, 9, 3, -8, 5, -19, 3, 4, 4, -26, -1, -18, 7, -6, -28, -7, -5, 0, 4, -7, 9, -16, 9, -2, 4, -8, 2, -1, 19, 3, -20, -24, -6, 1, 5, -12, -3, -23, -1, 24, 12, -16, -6, -9, -2, -1, -17, -22, -5, 5, 6, -10, 1, -17, 4, 2, 6, -27, -7, -22, 7, -6, -23, 5, -11, -4, 3, 7, 4, -10, -10, -22, 5, -28, -6, -24, -1, -1, -16, 12, -1, -1, 4, -2, 1, -25, 10, -9, 4, -12, -7, -13, 3, -1, -35, 17, -12, 2, 9, 2, -1, -8, -7, 22, 16, -24, 3, -13, 7, 2, -33, 22, -19, -4, 15, -1, 1, -14, 7, 4, 15, -15, -10, -9, 12, 6, -32, -4, -4, -1, 16, 0, 2, -13, -3, 6, 7, -30, -5, -8, 6, 0, -30, -2, -14, 4, -1, 2, -6, -15, 22, 15, -6, -35, -17, -10, 3, 3, -44, -26, -9, 4, 4, 1, 4, -26, -2, 0, 1, -12, 6, -6, -2, 0, -33, -26, -6, 3, 3, 5, 3, -17, 18, -4, 4, -33, -9, -12, 13, 9, -19, -8, -10, -4, 1, 0, -5, -26, 9, -16, 5, -39, 6, -22, 12, -2, -30, 20, -9, 5, 7, -1, 10, -15, 20, 15, 2, -42, -9, -15, 6, 0, -32, -1, -11, 3, 4, 0, 4, -15, 21, -13, 6, -31, 1, -12, -5, -17, -36, -7, -65, 1, 2, -2, 11, -19, -20, 24, 12, -49, -4, -21, 
};
const TfArray<2, int> tensor_dimension7 = { 2, { 4,400 } };
const TfArray<1, float> quant7_scale = { 1, { 0.0313454270362854, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data8[16] = { -8960, -4, -675, -2634, -773, 37, 269, 13, -3117, -703, -1481, 77, -220, -676, -654, -2, };
const TfArray<1, int> tensor_dimension8 = { 1, { 16 } };
const TfArray<16, float> quant8_scale = { 16, { 0.00026766897644847631, 0.0026306901127099991, 0.00085669383406639099, 0.00055707863066345453, 0.00060970132471993566, 0.0012668438721448183, 0.0013279895065352321, 0.0014308643294498324, 0.00043044830090366304, 0.00060951919294893742, 0.00065454735886305571, 0.0014884633710607886, 0.00048983335727825761, 0.00080638995859771967, 0.00057743821525946259, 0.0024240477941930294, } };
const TfArray<16, int> quant8_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data9[16*1*3*8] = { 
  /* [0][0][][] */ -11,35,23,28,3,-112,-10,89, 18,14,-69,-57,4,-20,-2,-34, -23,-8,44,127,66,-93,105,2, 
  /* [1][0][][] */ -26,-2,-8,-2,0,-127,0,0, -26,-2,-2,-21,6,-73,0,4, -9,7,-1,-24,-23,-7,0,-4, 
  /* [2][0][][] */ -7,4,-6,-87,-19,-89,-25,3, -9,1,-17,-127,39,-40,-6,21, -8,5,-31,-81,-4,-21,42,-3, 
  /* [3][0][][] */ -31,-36,-8,-28,-28,-39,-3,8, -16,-14,-111,30,-36,68,1,-27, -67,-23,-56,41,-35,-56,-1,-127, 
  /* [4][0][][] */ -28,-51,-3,-52,-127,-96,-1,-6, -15,-25,-8,-20,-25,-12,44,14, 27,-9,-10,-20,-29,48,-12,24, 
  /* [5][0][][] */ -3,4,-4,1,-10,-68,-127,12, -2,-4,6,-1,11,-42,-120,-8, -2,2,-1,21,1,-23,-81,-7, 
  /* [6][0][][] */ 0,-4,-3,-15,-11,-89,-19,-33, 9,-3,-5,-71,-12,-69,-17,-4, -2,-6,-9,-19,-16,-127,-14,-70, 
  /* [7][0][][] */ -6,-61,6,-106,-22,19,-2,4, -14,-117,13,-127,-46,-2,-2,4, -12,-22,-15,-112,-41,7,-4,6, 
  /* [8][0][][] */ -2,10,68,74,-19,5,-87,60, -6,-19,-55,-37,-37,16,-127,4, 32,-14,-15,-29,-12,32,-14,34, 
  /* [9][0][][] */ 24,7,-5,-9,-7,-46,54,10, -17,-21,-2,-64,-127,-84,-17,0, -27,-25,-15,-65,-86,71,-30,-10, 
  /* [10][0][][] */ -54,-119,-127,-31,-66,-23,-11,-2, -20,-79,-114,-22,-54,39,-49,2, -1,-22,-27,4,15,56,11,11, 
  /* [11][0][][] */ -95,-91,-68,-4,-19,10,-56,-36, -127,-108,-102,-9,-38,-85,-8,-39, -80,-109,-16,1,-39,-20,1,-36, 
  /* [12][0][][] */ -11,-36,-86,58,-2,3,-2,-7, -38,-127,-38,-33,-37,-9,-28,7, -10,-49,-5,-4,-43,12,-17,5, 
  /* [13][0][][] */ -22,-56,-7,-52,-50,52,10,1, -19,-127,2,-112,-3,-6,-4,-5, -17,-24,33,-31,19,-10,-3,53, 
  /* [14][0][][] */ 9,-31,-22,4,-75,27,-125,-80, -2,-25,21,-19,-79,127,-6,-69, 14,-32,-2,-59,-63,-13,8,-57, 
  /* [15][0][][] */ -90,-1,4,-10,5,-19,-10,19, -127,0,-5,-8,4,-16,-10,-3, -68,-1,9,-6,-3,4,-6,5, 
};
const TfArray<4, int> tensor_dimension9 = { 4, { 16,1,3,8 } };
const TfArray<16, float> quant9_scale = { 16, { 0.0066274376586079597, 0.06513543426990509, 0.021211592480540276, 0.013793171383440495, 0.015096099115908146, 0.031366836279630661, 0.032880790531635284, 0.03542795404791832, 0.010657825507223606, 0.015091590583324432, 0.01620648056268692, 0.036854095757007599, 0.012128190137445927, 0.01996607705950737, 0.014297271147370338, 0.060019005089998245, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data10[8] = { 222, -3477, -5423, -231, -5242, 543, -1734, 981, };
const TfArray<1, int> tensor_dimension10 = { 1, { 8 } };
const TfArray<8, float> quant10_scale = { 8, { 0.00012257526395842433, 7.6173673733137548e-05, 0.00015811953926458955, 0.00020185258472338319, 7.8742654295638204e-05, 0.00024486277834512293, 0.00012559261813294142, 0.00023258574947249144, } };
const TfArray<8, int> quant10_zero = { 8, { 0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data11[8*1*3*40] = { 
  /* [0][0][][] */ -127,69,19,31,-39,-10,-10,-16,2,4,-7,-9,3,-11,3,-6,-31,7,-8,23,-11,-14,1,-3,-12,-20,-11,-44,-35,-26,-18,33,52,35,21,12,-9,-6,44,47, -92,50,-42,10,-3,18,32,-12,-24,-44,-6,2,-25,-2,-1,-20,-31,-14,-11,3,-13,-4,3,-6,-20,-31,-9,-40,-36,-8,-5,26,48,40,35,13,-1,16,42,59, -61,-8,42,12,33,1,-32,-7,8,19,-13,-3,-25,-10,-4,19,-13,-1,6,12,-4,-1,9,-4,-2,-22,-8,-36,-16,15,-4,-8,34,26,23,-2,-15,8,36,43, 
  /* [1][0][][] */ 47,25,-91,-75,-53,-70,-90,-2,5,52,-12,-81,24,37,11,-15,32,7,1,7,-16,-8,-7,11,-11,16,-24,32,-7,22,-17,10,50,35,9,17,43,49,13,-28, 63,70,2,29,33,11,62,81,9,67,17,-86,25,21,-47,-38,26,-45,-58,-25,-17,-4,-21,4,-27,7,-36,19,-31,16,-55,2,41,44,5,5,16,43,10,-11, 6,-4,-127,-1,-9,-44,-5,-14,-44,88,-17,-67,34,41,-24,-14,18,-3,-15,0,3,15,-14,19,-21,24,-37,33,-15,15,-36,-24,42,13,4,6,21,42,-11,-11, 
  /* [2][0][][] */ -5,-54,37,15,29,2,19,-2,5,3,-5,2,7,-10,-18,-3,-13,-20,11,-4,15,13,-21,-22,-27,0,14,13,2,-2,-67,10,29,-15,-9,-1,45,6,-9,34, -4,-47,23,-5,26,21,14,-5,10,-2,0,0,0,1,-12,-2,-17,-20,5,7,16,23,-16,-15,-16,4,12,16,-13,-12,-60,7,15,-9,-5,1,23,0,-20,19, -110,-127,35,18,33,14,13,0,-4,-25,-8,2,16,1,-12,4,1,-16,24,2,14,21,-24,-1,-13,-11,7,4,-18,-11,-59,-7,21,-13,3,25,34,6,-7,30, 
  /* [3][0][][] */ 58,-27,-18,-12,-7,-32,-39,-13,7,-13,3,8,3,6,-7,-4,-10,-12,0,-5,-14,-11,-9,6,3,-1,2,10,18,15,16,6,2,5,9,11,36,43,9,55, 106,-9,-19,17,-13,-25,-2,-17,3,-5,-23,-12,10,3,-5,5,-8,-16,3,8,0,7,9,11,1,-12,-12,-6,-3,-4,-2,-11,-4,-17,-13,-21,-1,-9,-26,2, 127,-23,-26,-22,-10,-14,-28,-16,-9,-31,24,10,8,7,-2,-2,-9,-17,8,8,-17,-2,3,0,6,-3,-4,9,18,-8,3,3,-13,-19,-5,-5,12,0,-17,0, 
  /* [4][0][][] */ 35,-1,-4,-29,-64,-3,19,-22,-11,26,17,55,-14,-23,75,36,-110,-32,-12,-76,-57,-12,19,-25,36,18,-23,-5,-20,-20,-48,-20,29,18,37,28,-35,-16,127,32, 25,14,-35,-26,-66,7,30,-52,20,30,19,96,-10,-46,60,57,-93,0,29,-57,-16,-2,25,-5,38,9,-5,-19,-43,-26,-71,-28,24,18,38,53,-30,-28,110,13, -2,5,4,-25,-71,22,67,-40,-32,2,-1,78,-26,-53,37,29,-123,-48,54,-86,-13,21,8,-4,43,5,-26,-23,-42,-19,-56,-31,36,18,25,36,-29,-31,87,7, 
  /* [5][0][][] */ 21,3,9,8,25,19,-3,39,3,-33,-44,-29,-65,-123,-27,-19,-22,5,12,39,9,-18,1,-4,10,-25,-3,2,8,24,-7,-18,-16,-1,22,-12,-4,-1,26,20, -1,-36,4,-1,-5,5,-24,-22,-11,-76,-100,-59,-25,-127,5,6,-24,-25,5,-3,-3,0,-1,10,13,7,-3,-2,-9,1,-19,-14,-13,10,6,-4,8,-8,19,13, -54,-43,4,-9,-6,-27,-8,-34,-29,-15,-73,-39,5,-71,20,46,36,22,-8,-23,-30,-14,5,0,15,0,-18,-11,0,-9,-5,8,-3,8,-4,-21,7,-3,13,24, 
  /* [6][0][][] */ -4,-46,22,-14,8,8,6,12,29,19,-2,2,13,3,-10,-24,-21,-4,-3,-1,12,5,-17,-9,30,-9,-1,17,23,4,0,-7,-34,-30,-41,-6,13,42,67,-109, 8,-41,32,-8,23,12,2,6,15,15,-2,-9,5,-1,4,-9,-17,-18,-6,-4,-11,-15,-16,-12,9,8,6,23,-1,-5,21,25,-17,-11,-32,-9,36,41,71,-127, 18,-35,31,-11,19,6,-5,1,2,18,-5,-11,4,-11,-9,-12,-25,-26,-3,-2,5,-1,4,3,10,9,0,-2,-21,-7,20,29,7,-3,-24,0,28,27,71,-91, 
  /* [7][0][][] */ 24,-2,1,17,7,9,-5,3,-3,-13,-6,2,-12,0,0,-3,-11,1,-11,12,-7,-7,-17,-2,-19,11,-4,2,12,4,-30,17,15,17,-17,-31,-6,12,26,-36, -4,-34,-9,3,-11,3,-7,17,8,-2,-6,3,1,9,-2,-7,2,-9,-3,5,0,0,-6,9,-2,10,0,8,7,1,-35,11,10,18,9,8,9,-4,18,-51, -89,-127,-32,-11,-11,-7,-11,10,-1,-8,-12,3,6,14,-16,-5,12,-1,-15,-1,1,13,3,12,-7,2,-14,-12,-5,-5,-32,11,-1,2,-9,21,25,14,42,-56, 
};
const TfArray<4, int> tensor_dimension11 = { 4, { 8,1,3,40 } };
const TfArray<8, float> quant11_scale = { 8, { 0.031379267573356628, 0.019500460475683212, 0.040478602051734924, 0.051674261689186096, 0.02015811949968338, 0.062684871256351471, 0.032151710242033005, 0.059541951864957809, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant10_zero, 0 };
const TfArray<4, int> tensor_dimension12 = { 4, { 1,1,99,40 } };
const TfArray<4, int> tensor_dimension13 = { 4, { 1,1,99,8 } };
const TfArray<1, float> quant13_scale = { 1, { 0.040388002991676331, } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension14 = { 4, { 1,99,1,8 } };
const TfArray<4, int> tensor_dimension15 = { 4, { 1,50,1,8 } };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,1,50,8 } };
const TfArray<4, int> tensor_dimension17 = { 4, { 1,1,50,16 } };
const TfArray<1, float> quant17_scale = { 1, { 0.023647278547286987, } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension18 = { 4, { 1,50,1,16 } };
const TfArray<4, int> tensor_dimension19 = { 4, { 1,25,1,16 } };
const TfArray<2, int> tensor_dimension20 = { 2, { 1,400 } };
const TfArray<2, int> tensor_dimension21 = { 2, { 1,4 } };
const TfArray<1, float> quant21_scale = { 1, { 0.33969846367835999, } };
const TfArray<1, int> quant21_zero = { 1, { 57 } };
const TfLiteAffineQuantization quant21 = { (TfLiteFloatArray*)&quant21_scale, (TfLiteIntArray*)&quant21_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 12 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 12,11,10 } };
const TfArray<1, int> outputs1 = { 1, { 13 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 13,2 } };
const TfArray<1, int> outputs2 = { 1, { 14 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 14 } };
const TfArray<1, int> outputs3 = { 1, { 15 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 15,3 } };
const TfArray<1, int> outputs4 = { 1, { 16 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 16,9,8 } };
const TfArray<1, int> outputs5 = { 1, { 17 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 17,4 } };
const TfArray<1, int> outputs6 = { 1, { 18 } };
const TfLitePoolParams opdata7 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs7 = { 1, { 18 } };
const TfArray<1, int> outputs7 = { 1, { 19 } };
const TfLiteReshapeParams opdata8 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs8 = { 2, { 19,5 } };
const TfArray<1, int> outputs8 = { 1, { 20 } };
const TfLiteFullyConnectedParams opdata9 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs9 = { 3, { 20,7,6 } };
const TfArray<1, int> outputs9 = { 1, { 21 } };
const TfLiteSoftmaxParams opdata10 = { 1 };
const TfArray<1, int> inputs10 = { 1, { 21 } };
const TfArray<1, int> outputs10 = { 1, { 22 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 3968), (TfLiteIntArray*)&g0::tensor_dimension0, 3960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 1600, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 384, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension11, 960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension12, 3960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 3968), (TfLiteIntArray*)&g0::tensor_dimension13, 792, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension14, 792, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension15, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension16, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension17, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension18, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension19, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension20, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 400), (TfLiteIntArray*)&g0::tensor_dimension21, 4, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension21, 4, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 23, };
const size_t tflNodes_subgraph_index[] = {0, 11, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  22, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_1078757_3_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 23;
  for (size_t i = 0; i < 23; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1078757_3_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1078757_3_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1078757_3_invoke() {
  for (size_t i = 0; i < 11; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1078757_3_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
