[platformio]
; Khong de OneDrive dong bo/khoa file .o trong luc PlatformIO dang build.
build_dir = C:/Users/E14/.platformio/build/AI_SOUND

[env:esp32-s3-devkitc-1]
platform = platformio/espressif32
; Board local cho module N8R8 (8 MB Flash + 8 MB PSRAM).
board = esp32-s3-n8r8
framework = arduino

monitor_speed = 115200
upload_speed = 115200

board_build.flash_mode = qio
board_build.partitions = huge_app.csv
board_build.psram_type = opi

; ESP32-S3 + PSRAM OPI
board_build.arduino.memory_type = qio_opi

lib_deps =
    johnosbb/MicroTFLite @ ^1.0.4

build_flags =
    -O2
    -DCORE_DEBUG_LEVEL=3
