// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchoolGuardian.Api.Data;
using SchoolGuardian.Api.Models;

#nullable disable

namespace SchoolGuardian.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "AlertStatus", new[] { "pending", "confirmed", "false_alarm", "resolved" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "DeviceStatus", new[] { "online", "offline", "error" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "Role", new[] { "admin", "ban_giam_hieu", "giam_thi", "bao_ve", "phu_huynh" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "SoundType", new[] { "scream", "help", "threat", "argument" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SchoolGuardian.Api.Models.Alert", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AudioFileUrl")
                        .HasColumnType("text")
                        .HasColumnName("audio_file_url");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence_score");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<string>("HandledById")
                        .HasColumnType("text")
                        .HasColumnName("handled_by_id");

                    b.Property<bool>("IsEvidence")
                        .HasColumnType("boolean")
                        .HasColumnName("is_evidence");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<SoundType>("SoundType")
                        .HasColumnType("SoundType")
                        .HasColumnName("sound_type");

                    b.Property<AlertStatus>("Status")
                        .HasColumnType("AlertStatus")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("HandledById");

                    b.ToTable("alerts");
                });

            modelBuilder.Entity("SchoolGuardian.Api.Models.AlertLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_id");

                    b.Property<string>("AlertId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alert_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("AlertId");

                    b.ToTable("alert_logs");
                });

            modelBuilder.Entity("SchoolGuardian.Api.Models.Area", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("areas");
                });

            modelBuilder.Entity("SchoolGuardian.Api.Models.Device", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("area_id");

                    b.Property<int>("BatteryLevel")
                        .HasColumnType("integer")
                        .HasColumnName("battery_level");

                    b.Property<int>("Floor")
                        .HasColumnType("integer")
                        .HasColumnName("floor");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double>("PositionX")
                        .HasColumnType("double precision")
                        .HasColumnName("position_x");

                    b.Property<double>("PositionY")
                        .HasColumnType("double precision")
                        .HasColumnName("position_y");

                    b.Property<DeviceStatus>("Status")
                        .HasColumnType("DeviceStatus")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("devices");
                });

            modelBuilder.Entity("SchoolGuardian.Api.Models.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("settings");
                });

            modelBuilder.Entity("SchoolGuardian.Api.Models.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ClassroomId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("classroom_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("ParentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parent_id");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("ParentId");

                    b.ToTable("students");
                });

            modelBuilder.Entity("SchoolGuardian.Api.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<Role>("Role")
                        .HasColumnType("Role")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("SchoolGuardian.Api.Models.Alert", b =>
                {
                    b.HasOne("SchoolGuardian.Api.Models.Device", "Device")
                        .WithMany("Alerts")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolGuardian.Api.Models.User", "HandledBy")
                        .WithMany("HandledAlerts")
                        .HasForeignKey("HandledById");

                    b.Navigation("Device");

                    b.Navigation("HandledBy");
                });

            modelBuilder.Entity("SchoolGuardian.Api.Models.AlertLog", b =>
                {
                    b.HasOne("SchoolGuardian.Api.Models.User", "Actor")
                        .WithMany("AlertLogs")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolGuardian.Api.Models.Alert", "Alert")
                        .WithMany("Logs")
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Alert");
                });

            modelBuilder.Entity("SchoolGuardian.Api.Models.Device", b =>
                {
                    b.HasOne("SchoolGuardian.Api.Models.Area", "Area")
                        .WithMany("Devices")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("SchoolGuardian.Api.Models.Student", b =>
                {
                    b.HasOne("SchoolGuardian.Api.Models.Area", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolGuardian.Api.Models.User", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SchoolGuardian.Api.Models.Alert", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("SchoolGuardian.Api.Models.Area", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("SchoolGuardian.Api.Models.Device", b =>
                {
                    b.Navigation("Alerts");
                });

            modelBuilder.Entity("SchoolGuardian.Api.Models.User", b =>
                {
                    b.Navigation("AlertLogs");

                    b.Navigation("HandledAlerts");
                });
#pragma warning restore 612, 618
        }
    }
}
